### ISSUE TITLE
Cannot generated new beshify

### ISSUE THREAD

**Issue by allestaire** [Phnumbahwan/Beshify#1]
## Steps to reproduce

1. Enter a text
2. Generate
3. Enter another text
4. Once click the airplane icon
5. The generated text will not change

https://github.com/Phnumbahwan/Beshify/assets/68372409/c49b9dd8-a60f-4688-a7a1-69e86c623025

**Comment by Phnumbahwan** [comment]
I think you should wait for the button animation to stop before clicking. @allestaire
